version: '3.8'
services:
  pickaxe:
    extends:
      file: docker.config.yml
      service: pickaxe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
      - "4990:4990"
