FROM golang:1.14.3

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/githubnemo/CompileDaemon
RUN go get github.com/ctrlrsf/logdna/cmd/logdna-stdin

WORKDIR /go/src/github.com/myriadeinc/pickaxe/

COPY . .

ENTRYPOINT dep ensure && CompileDaemon -build="go build -o ./build/pickaxe ./src/main.go" -command="./build/pickaxe"