# iron/go:dev is the alpine image with the go tools added
FROM golang:1.10
RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/myriadeinc/pickaxe/

COPY . .

RUN dep ensure

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]

# Hot reloading build for development
ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o ./build/pickaxe ./src/main.go" -command="./build/pickaxe"