version: '3.8'
services:
  pickaxe:
    logging:
      options:
        max-size: "10m"
    environment:
      WEBHOOK_URL: http://zircon:4990/new
      WALLET_ADDRESS: 47PAULmUFo3DPHKehGPuxXbEAB4JkRYJ49DEFs4EqaT7M2TRqqWWHAeJyEHWg8eRoWNwMAHh7bx6Eh5SR2fpdnj71fhxugC
      RESERVE_OFFSET: 8
      