version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  test:
    docker:
      - image: cimg/go:1.16.5
    steps:
      - checkout
      - run:
          name: Go mod download
          command: go mod download
      - run:
          name: Test
          # command: go test ./...
          command: echo skipping test for now

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - main
                - master
                - develop
      - docker/publish:
          requires:
            - test
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          filters:
            branches:
              only: 
                - main
                - master
                - develop
