service:
  name: pickaxe
  host: https://0.0.0.0:8050
  shared_secret: "__REPLACE__"
pool:
  wallet_address: "9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8"
  monero_url: "http://daemon.myriade.io/json_rpc"